name: Bash Check

on:
  pull_request:
    paths:
      - "**/*.sh"
      - "justfile"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "**/*.sh"
      - "justfile"
      - ".github/workflows/check.yml"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Install shell tools
        run: |
          sudo apt-get update
          sudo apt-get install -y just shellcheck shfmt

      - name: Run checks
        run: just check
